//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBCourseWork2Airlinesite.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.qatarairways.com", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GrabCodeResult from namespace http://www.qatarairways.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qatarairways.com/GrabCode", ReplyAction="*")]
        WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponse GrabCode(WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qatarairways.com/GrabCode", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponse> GrabCodeAsync(WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabCode", Namespace="http://www.qatarairways.com", Order=0)]
        public WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequestBody Body;
        
        public GrabCodeRequest() {
        }
        
        public GrabCodeRequest(WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GrabCodeRequestBody {
        
        public GrabCodeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabCodeResponse", Namespace="http://www.qatarairways.com", Order=0)]
        public WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponseBody Body;
        
        public GrabCodeResponse() {
        }
        
        public GrabCodeResponse(WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.qatarairways.com")]
    public partial class GrabCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GrabCodeResult;
        
        public GrabCodeResponseBody() {
        }
        
        public GrabCodeResponseBody(string GrabCodeResult) {
            this.GrabCodeResult = GrabCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WEBCourseWork2Airlinesite.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WEBCourseWork2Airlinesite.ServiceReference1.WebService1Soap>, WEBCourseWork2Airlinesite.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponse WEBCourseWork2Airlinesite.ServiceReference1.WebService1Soap.GrabCode(WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest request) {
            return base.Channel.GrabCode(request);
        }
        
        public string GrabCode() {
            WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest inValue = new WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest();
            inValue.Body = new WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequestBody();
            WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponse retVal = ((WEBCourseWork2Airlinesite.ServiceReference1.WebService1Soap)(this)).GrabCode(inValue);
            return retVal.Body.GrabCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponse> WEBCourseWork2Airlinesite.ServiceReference1.WebService1Soap.GrabCodeAsync(WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest request) {
            return base.Channel.GrabCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeResponse> GrabCodeAsync() {
            WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest inValue = new WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequest();
            inValue.Body = new WEBCourseWork2Airlinesite.ServiceReference1.GrabCodeRequestBody();
            return ((WEBCourseWork2Airlinesite.ServiceReference1.WebService1Soap)(this)).GrabCodeAsync(inValue);
        }
    }
}
